In [1]:
with open("Data/the-verdict.txt","r", encoding="utf-8") as f:
    raw_text=f.read()

In [2]:
import gensim.downloader as api

In [3]:
model = api.load("word2vec-google-news-300")

In [4]:
word_vectors=model

In [5]:
print(word_vectors['computer'])

[ 1.07421875e-01 -2.01171875e-01  1.23046875e-01  2.11914062e-01
 -9.13085938e-02  2.16796875e-01 -1.31835938e-01  8.30078125e-02
  2.02148438e-01  4.78515625e-02  3.66210938e-02 -2.45361328e-02
  2.39257812e-02 -1.60156250e-01 -2.61230469e-02  9.71679688e-02
 -6.34765625e-02  1.84570312e-01  1.70898438e-01 -1.63085938e-01
 -1.09375000e-01  1.49414062e-01 -4.65393066e-04  9.61914062e-02
  1.68945312e-01  2.60925293e-03  8.93554688e-02  6.49414062e-02
  3.56445312e-02 -6.93359375e-02 -1.46484375e-01 -1.21093750e-01
 -2.27539062e-01  2.45361328e-02 -1.24511719e-01 -3.18359375e-01
 -2.20703125e-01  1.30859375e-01  3.66210938e-02 -3.63769531e-02
 -1.13281250e-01  1.95312500e-01  9.76562500e-02  1.26953125e-01
  6.59179688e-02  6.93359375e-02  1.02539062e-02  1.75781250e-01
 -1.68945312e-01  1.21307373e-03 -2.98828125e-01 -1.15234375e-01
  5.66406250e-02 -1.77734375e-01 -2.08984375e-01  1.76757812e-01
  2.38037109e-02 -2.57812500e-01 -4.46777344e-02  1.88476562e-01
  5.51757812e-02  5.02929

In [ ]:
#King + Women-Man=?

In [6]:
print(word_vectors.most_similar(positive=['king','women'],negative=['man'],topn=10))

[('queen', 0.4827326238155365), ('queens', 0.466781347990036), ('kumaris', 0.4653734564781189), ('kings', 0.4558638632297516), ('womens', 0.422832190990448), ('princes', 0.4176960587501526), ('Al_Anqari', 0.41725507378578186), ('concubines', 0.4011078476905823), ('monarch', 0.39624831080436707), ('monarchy', 0.39430153369903564)]


In [7]:
# Example of calculating similarity
print (word_vectors.similarity ('woman', 'man'))
print (word_vectors.similarity('king', 'queen'))
print(word_vectors.similarity ('uncle', 'aunt'))
print(word_vectors.similarity('boy', 'girl'))
print (word_vectors.similarity('nephew', 'niece'))
print (word_vectors.similarity( 'paper', 'water'))

0.76640123
0.6510957
0.76434743
0.8543272
0.7594367
0.11408083


## Most similar Words

In [8]:
print(word_vectors.most_similar("tower",topn=5))

[('towers', 0.8531749248504639), ('skyscraper', 0.6417425870895386), ('Tower', 0.639177143573761), ('spire', 0.5946877598762512), ('responded_Understood_Atlasjet', 0.5931612849235535)]


## Lets See Vector similarity

In [9]:
import numpy as np

#words to compare
word1= 'man'
word2='woman'

word3= 'semiconductor'
word4='earthworm'

word5= 'newhew'
word6='niece'

#calculate the vector difference
 
vector_difference1=model[word1]=model[word2]
vector_difference2=model[word3]=model[word4]
vector_difference3=model[word5]=model[word6]

#Calcualte the magnitude of the vector difference
magnitude_of_difference1 = np.linalg.norm(vector_difference1)
magnitude_of_difference2 = np.linalg.norm(vector_difference2)
magnitude_of_difference3 = np.linalg.norm(vector_difference3)

print("The magnitude of the difference between '{}' and '{}' is {:.2f}".format(word1,word2,magnitude_of_difference1))
print("The magnitude of the difference between '{}' and '{}' is {:.2f}".format(word3,word4,magnitude_of_difference2))
print("The magnitude of the difference between '{}' and '{}' is {:.2f}".format(word5,word6,magnitude_of_difference3))




The magnitude of the difference between 'man' and 'woman' is 2.66
The magnitude of the difference between 'semiconductor' and 'earthworm' is 4.27
The magnitude of the difference between 'newhew' and 'niece' is 2.87


## Creating token embedding 

In [ ]:
# let's say we have 4 token ids
# suppose vecotrs 'quick', 'fox', 'is', 'in', 'the', 'house'
#we will arrange them in assending order and assing token ids
#'quick'->[4], 'fox'->[0], 'is'->[3], 'in'->[2], 'the'->[5], 'house'->[1]


In [12]:
pip install torch

python(4178) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.


  Using cached mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 150.8/150.8 MB 3.0 MB/s  0:00:48m0:00:0100:02
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 6.1 MB/s  0:00:00 eta 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.3/6.3 MB 6.5 MB/s  0:00:00 eta 0:00:01
Using cached mpmath-1.3.0-py3-none-any.whl (536 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6/6 [torch]32m5/6 [torch]]x]
Note: you may need to restart the kernel to use updated packages.


In [2]:
import torch

In [4]:
input_ids= torch.tensor([2,3,5,1])

In [5]:
# now we will take vocabulary size 6 as we have 6 words
# and vector dimensions / weights =3

vocab_size=6
output_dim= 3
torch.manual_seed(123)
embedding_layer= torch.nn.Embedding(vocab_size,output_dim)

In [6]:
#The print statement in the code prints the embedding layer's underlying weight matrix:
print(embedding_layer.weight)

Parameter containing:
tensor([[ 0.3374, -0.1778, -0.1690],
        [ 0.9178,  1.5810,  1.3010],
        [ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-1.1589,  0.3255, -0.6315],
        [-2.8400, -0.7849, -1.4096]], requires_grad=True)


In [7]:
 print(embedding_layer(torch.tensor([3])))

tensor([[-0.4015,  0.9666, -1.1481]], grad_fn=<EmbeddingBackward0>)


In [9]:
#If we compare the embedding vector for token ID 3 to the previous embedding matrix, 
#we see that it is identical to the 4th row


# What is an embedding layer?
#the embedding layer is essentially a look-up operation that retrieves
#rows from the embedding layer's weight matrix via a token


In [8]:
print(embedding_layer(input_ids))

tensor([[ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-2.8400, -0.7849, -1.4096],
        [ 0.9178,  1.5810,  1.3010]], grad_fn=<EmbeddingBackward0>)


In [ ]:
#Each row in this output matrix is obtained via a lookup operation from the embedding weight matrix

In [ ]:
# Both embedding layer and Neural Network linear layer lead to same output
# Embedding layer is much more computationally efficient, since NN linear layer has many
# unnecessary multiplications with zero.